export default [{'simp': '遗憾',
  'pron': 'yí hàn',
  'defi': 'regret; to regret; to be sorry that'},
 {'simp': '办事处', 'pron': 'bàn shì chù', 'defi': 'office; agency'},
 {'simp': '拖鞋', 'pron': 'tuō xié', 'defi': 'slippers; sandals; flip-flops'},
 {'simp': '策略', 'pron': 'cè lüè', 'defi': 'strategy; tactics; crafty; adroit'},
 {'simp': '常规',
  'pron': 'cháng guī',
  'defi': 'code of conduct; conventions; common practice; routine (medical procedure etc)'},
 {'simp': '奉献',
  'pron': 'fèng xiàn',
  'defi': 'to offer respectfully; to consecrate; to dedicate; to devote'},
 {'simp': '酱油', 'pron': 'jiàng yóu', 'defi': 'soy sauce'},
 {'simp': '母女', 'pron': 'mǔ nǚ', 'defi': 'mother-daughter'},
 {'simp': '一齐', 'pron': 'yī qí', 'defi': 'at the same time; simultaneously'},
 {'simp': '升学', 'pron': 'shēng xué', 'defi': 'to enter the next grade school'},
 {'simp': '国产', 'pron': 'guó chǎn', 'defi': 'domestically produced'},
 {'simp': '为此',
  'pron': 'wèi cǐ',
  'defi': 'for this reason; with regards to this; in this respect; in order to do this; to this end'},
 {'simp': '景', 'pron': 'jǐng', 'defi': 'bright; circumstance; scenery'},
 {'simp': '用品',
  'pron': 'yòng pǐn',
  'defi': 'articles for use; products; goods'},
 {'simp': '野',
  'pron': 'yě',
  'defi': 'field; plain; open space; limit; boundary; rude; feral'},
 {'simp': '用得着',
  'pron': 'yòng de zháo',
  'defi': 'to be able to use; useable; to have a use for sth; (in interrogative sentence) to be necessary to'},
 {'simp': '跨',
  'pron': 'kuà',
  'defi': 'to step across; to stride over; to straddle; to span'},
 {'simp': '成',
  'pron': 'chéng',
  'defi': 'to succeed; to finish; to complete; to accomplish; to become; to turn into; to be all right; OK!; one tenth'},
 {'simp': '地下室', 'pron': 'dì xià shì', 'defi': 'basement; cellar'},
 {'simp': '之类', 'pron': 'zhī lèi', 'defi': 'and so on; and such'},
 {'simp': '横',
  'pron': 'héng',
  'defi': 'horizontal; across; (horizontal character stroke)'},
 {'simp': '师生', 'pron': 'shī shēng', 'defi': 'teachers and students'},
 {'simp': '驻',
  'pron': 'zhù',
  'defi': 'to halt; to stay; to be stationed (of troops, diplomats etc)'},
 {'simp': '妙', 'pron': 'miào', 'defi': 'clever; wonderful'},
 {'simp': '罪恶', 'pron': 'zuì è', 'defi': 'crime; evil; sin'},
 {'simp': '氧气', 'pron': 'yǎng qì', 'defi': 'oxygen'},
 {'simp': '没收', 'pron': 'mò shōu', 'defi': 'to confiscate; to seize'},
 {'simp': '箭', 'pron': 'jiàn', 'defi': 'arrow'},
 {'simp': '当',
  'pron': 'dàng',
  'defi': 'at or in the very same...; suitable; adequate; fitting; proper; to replace; to regard as; to think; to pawn; (coll.) to fail (a student)'},
 {'simp': '如', 'pron': 'rú', 'defi': 'as; as if; such as'}];


